[theme]
primaryColor="#5bbf83"
backgroundColor="#ffffff"
secondaryBackgroundColor="#ebebeb"
textColor="#333333"

[server]
maxUploadSize = 2000
enableStaticServing = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
